test
gdvl777/math_magicians pull request #6
Opened 2023-09-20 22:00 UTC by gdvl777

- [ ] Write unit tests with React Testing Library.

2023-09-21 16:37 UTC, topeogunleye commented
@gdvl777, can you please add the note from student success

2023-09-21 16:39 UTC, gdvl777 commented
> @gdvl777, can you please add the note from student success

I have communicated with them, but I haven't received a response from Student Success. I didn't want to wait any longer because time is running out to complete all my activities for this week.

2023-09-21 16:58 UTC, topeogunleye commented
> > @gdvl777, can you please add the note from student success
> 
> I have communicated with them, but I haven't received a response from Student Success. I didn't want to wait any longer because time is running out to complete all my activities for this week.

@gdvl777, When they reply. Attach their Note please

2023-09-21 16:58 UTC, topeogunleye commented
Hi @gdvl777, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the `student success` team and they'll permit you to work solo or look for a suitable partner. Attach a screenshot of the message you received from `student success` stating that you can do the project alone in the pull request description and resubmit this PR👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

2023-09-21 20:20 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @gdvl777, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that is pair-programming which means every member of the group must have a solid fair contributions to the PR commits. This milestone was assigned to three members only two people contributed. You need to receive a go ahead from student success before you can work solo. Kindly provide evidence from SS signalling to work alone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-21 21:55 UTC, LionRouge1 requested changes
Hi **Team**, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Set up React Testing Library :heavy_check_mark: 
- Write unit tests for the files `operate.js` and `calculate.js` using Jest :heavy_check_mark: 
- All linters passed :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 21:55 UTC, LionRouge1 commented on src/tests/operate.test.js
- [ ] Nice work writing unit tests for the files `operate.js` and `calculate.js` using Jest :clap: However it also requested in the project requirement to create unit tests for all React components(see image). Kindly write a tests for the components to follow the project requirement.
![Screenshot from 2023-09-21 21-42-23](https://github.com/gdvl777/math_magicians/assets/91142432/8c8f2670-ecf6-4afe-aa56-726c59886981)

2023-09-21 21:55 UTC, LionRouge1 commented on README.md
- [ ] According to GitHub history 3 persons contributed to this project, but we have only one person information under the **Authors** section. Kindly make sure we have all the authors listed in the **Authors** section to make your README file looks more professional.

2023-09-21 21:55 UTC, LionRouge1 commented on README.md
> +> This project is [MIT](https://github.com/gdvl777/math_magicians/blob/develop/MIT.md).
- [ ] Please note that the license link is linked to a 404 page. Kindly make sure there is no broken link in your README file. That will show your attention to detail and your professionalism.

2023-09-22 07:59 UTC, bambzee commented
Note for future code reviewers: Student Success **did not grant** permission to the student to work alone during this pair-programming week.

2023-09-22 15:47 UTC, Johnadibe requested changes
# Status: Required Changes ♻️
### Hi Team🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

### Kindly note that I am reviewing this PR because now all the students have a minimum code contribution.

 ## Highlights
- Implemented some of the changes requested by the previous reviewer✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 15:47 UTC, Johnadibe commented on src/tests/quote.test.js
> +});
> - [ ] Good job so far Team👍, While reviewing the unit test implementation, I encountered some errors that need attention. It's important to ensure that our tests are accurate and reliable to effectively assess our project. Could you please take a look at the unit tests you've written and address the errors?
> 
> ![err](https://github.com/gdvl777/math_magicians/assets/40009354/2486d0e6-5650-475d-a3ab-a063e1ce04cd)
> 
> ![err1](https://github.com/gdvl777/math_magicians/assets/40009354/dccac980-86a9-418d-8dff-2a2e7f9b2be2)
>

2023-09-22 18:36 UTC, julie-ify approved these changes
Hi @gdvl777, @Johnadibe,

## Highlights!
- Good code organization and tests ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 20:05 UTC, closed without merging